Create /isv contact-us form
canonical-web-and-design/microk8s.io pull request #518
Opened 2022-03-30 13:16 UTC by petesfrench

## Done

- Create /isv contact-us form [copydoc](https://docs.google.com/document/d/1zFVotFVMovmyx-Csqv_OEoB4uNMp69xOGi1WjENIU7A/edit)
- Update copy as per [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)

## QA

- Go to /isv compare against [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)
- Check the contact form opens and matches the [copydoc](https://docs.google.com/document/d/1zFVotFVMovmyx-Csqv_OEoB4uNMp69xOGi1WjENIU7A/edit)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/5005

2022-03-30 13:17 UTC, webteam-app commented
Demo starting at https://microk8s-io-518.demos.haus

2022-03-30 13:31 UTC, mtruj013 requested changes
Looks good! Just a couple of comments:

2022-03-30 13:31 UTC, mtruj013 commented on templates/isv/contact-us.html
> +                <label for="phone">Is your company a software vendor?</label>
This one's supposed to be a checkbox according to the doc

2022-03-30 13:52 UTC, petesfrench commented
@mtruj013 Thanks for the feedback! I have kept that one line deleted as for me it is deleted in the doc.

2022-03-30 13:52 UTC, petesfrench commented
@mtruj013 Thanks for the feedback! I have kept that one line deleted as for me it is deleted in the doc.

2022-03-31 11:30 UTC, mtruj013 approved these changes
LGTM!

2022-04-01 07:15 UTC, merged